---
title: "Compétition fiscale locale"
author: "Vincent Robitaille"
format: 
  revealjs:
    theme: dark
editor: visual
bibliography: references.bib
csl: apa.csl
---

## Motivation (5 diapo max)

## Motivation empirique

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Financement des biens publics locaux
:::
::::

-   Énoncer du problème (image, graphes, chiffres)
-   Importance du problème
-   Pertinence d'étudier ce problème

## Problématique

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Financement des municipalités
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
-   Routes municipales
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
-   Sécurité publique
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Défis économiques et politiques
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
-   Érosion de l'assiette fiscale
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
-   "Spill over" des externalités et des bénéfices
:::
::::

::: {.fragment .fade-in}
-   Satisfaction des électeurs
:::

## Motivation méthodologique

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Effets d'interaction
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Effets d'interaction
:::
::::

## Motivation méthodologique (suite)

```{dot}
digraph D {
 bgcolor="#181818";

  node [
    fontcolor = "#e6e6e6",
    style = filled,
    color = "#e6e6e6",
    fillcolor = "#333333"
  ]

  edge [
    color = "#e6e6e6",
    fontcolor = "#e6e6e6"
  ]
  Interaction; Censure; Latence;
  Censure->Latence;
  Interaction->Latence;
}
```

## Question de recherche (3 diapo max)

Quel est l'impact de la censure sur la modélisation des interactions dans un jeu de compétition fiscale locale ?  (À revoir)

## Justification

:::: {.fragment .fade-in}
Meilleure compréhension de la structure d'intéraction
::::
:::: {.fragment .fade-in}
- Validation de modèles théoriques
::::
:::: {.fragment .fade-in}
- Effets de l'application de seuils exogènes
::::


## Énoncé de l'hypothèse à tester (1 diapo)

Un modèle simultané (censuré) est-il mieux adapté qu'un modèle latent ?

:::: {.fragment .fade-in}
- Un modèle simultané devrait mieux performer
::::

## Contributions (2 diapo max)

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Meilleure comprehension du type d'interaction

- Comparaison des structures d'interaction
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Diversification des approches de modélisation

- Modèles spatiaux Tobit peu utilisés
:::
::::

## Littérature (4 diapo max)

-   Modèle bayésien latent avec intéraction et censure (litt)
-   Modèle spatial Tobit latent
-   Modèle spatial Tobit simultané

## Données et statistiques descriptives (OPTIONNEL, 5 à 10 diapo max)

**Nombre d'observations**:

**Variables**

## Théorie (5 à 10 diapo max)

## Modèle théorique

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Fonction de *payoff* [@yang2018]

$$r(\tau_i, \tau_{-i}, x_i) = -\gamma(\tau_i - x'_i\beta - \lambda \sum_{j\neq i}W_{n,ij}\tau_j-\varepsilon_i)^2$$
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Équilibre de Nash (information complète)

$$\tau_i^* = \max\left\{x_i'\beta + \lambda\sum_{j\neq i}W_{n,ij}\tau^*_j + \varepsilon_i, 0\right\}$$
:::
::::

## Modèle théorique - interpretation

Jeu en information complète

Interaction sur la variable observé (non latente)

## Économétrie bayesienne

Les paramètres sont des variables aléatoires

:::: {.fragment .fade-in}
Prior: $p\left(\theta_1, \theta_2, ..., \theta_k\right)$
::::
:::: {.fragment .fade-in}
Vraisemblance: $p\left(y|\theta_1, \theta_2, ..., \theta_k\right)$
::::
:::: {.fragment .fade-in}
Posterior: $p\left(\theta_1, \theta_2, ..., \theta_k|y\right)$
::::

## Théorème de Bayes

$$p(\theta|y) = \frac{p(\theta)p(y|\theta)}{p(y)}$$

:::: {.fragment .fade-in}
$$p(\theta|y) \propto p(\theta)p(y|\theta)$$
::::

## Économétrie spatiale

Modèle de lag spatial

$$y = \lambda W y + X\beta + \varepsilon, \quad E\left[\varepsilon|X\right] = 0$$ 
:::: {.fragment .fade-in}
Matrice de poids $W$ non-stochastique et exogène.
::::

:::: {.fragment .fade-in}
-   Contiguité
::::
:::: {.fragment .fade-in}
-   Distance
::::
:::: {.fragment .fade-in}
-   Etc.
::::

## Modèle censuré

Tobit: $y = \max\{0, y^*\}$

:::: {.fragment .fade-in}
Spatial Tobit (SAR) [@qu2012]
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
-   Modèle latent
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
-   Modèle simultané
:::
::::

## Spatial Tobit (SAR)

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Modèle latent

$$y_i = \max\left\{0, \lambda\sum_{j=1}^nw_{ij} y^*_j + x_i\beta + \varepsilon_i\right\}$$
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
Modèle simultané

$$y_i = \max\left\{0, \lambda\sum_{j=1}^nw_{ij} y_j + x_i\beta + \varepsilon_i\right\}$$
:::
::::

## Stratégie empirique (4 à 5 diapo)

-   Estimation des modèles avec différentes structures et variable latente vs censurée
-   Comparaison des modèles (bayes factor ?)

## Justification des hypothèses d'identification (1 à 2 diapo)

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
**Jeu en information complète**

-   Standard dans la littérature
-   Simplification
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
**Équilibre de Nash unique**

-   Nécessaire à la modélisation
-   Standard dans la littérature
:::
::::

:::: {.fragment .fade-in}
::: {.fragment .semi-fade-out}
**Matrice d'interactions non stochastique et exogène**

-   Standard dans la littérature
-   Simplification
:::
::::
## Références
